development:
  adapter: postgresql
  encoding: utf8
  database: ninevine_development
  username: postgres
  password: 143614
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: ninevine_test
  username: postgres
  password: 143614
  host: localhost